### ISSUE TITLE
readlink -f option not supported in macOS

### ISSUE THREAD

**Issue by huangguiyang** [aamine/cbc#3]
macOS 10.12

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Exception in thread "main" java.lang.NoClassDefFoundError: net/loveruby/cflat/compiler/Compiler
Caused by: java.lang.ClassNotFoundException: net.loveruby.cflat.compiler.Compiler
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by huangguiyang** [comment]
The compiler does not support macOS, even this problem can be fixed by `brew install coreutils`.
